<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = [
            // Electronics Categories
            [
                'tenant_id' => 1,
                'parent_id' => null,
                'level' => 0,
                'path' => 'electronics',
                'name' => 'Electronics',
                'slug' => 'electronics',
                'description' => 'Electronic devices and gadgets',
                'image' => 'https://via.placeholder.com/300x200/3498db/ffffff?text=Electronics',
                'banner_image' => 'https://via.placeholder.com/800x300/3498db/ffffff?text=Electronics+Banner',
                'icon' => 'fas fa-laptop',
                'color' => '#3498db',
                'sort_order' => 1,
                'is_active' => true,
                'is_featured' => true,
                'status' => true,
                'language' => 'en',
                'seo_title' => 'Electronics - Latest Gadgets & Devices',
                'seo_description' => 'Shop the latest electronics and gadgets',
                'seo_keywords' => 'electronics, gadgets, devices, technology',
                'canonical_url' => '/electronics',
                'commission_rate' => 3.50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'parent_id' => 1, // Electronics
                'level' => 1,
                'path' => 'electronics/smartphones',
                'name' => 'Smartphones',
                'slug' => 'smartphones',
                'description' => 'Latest smartphones and mobile devices',
                'image' => 'https://via.placeholder.com/300x200/2ecc71/ffffff?text=Smartphones',
                'icon' => 'fas fa-mobile-alt',
                'color' => '#2ecc71',
                'sort_order' => 1,
                'is_active' => true,
                'is_featured' => true,
                'status' => true,
                'language' => 'en',
                'seo_title' => 'Smartphones - Latest Mobile Devices',
                'seo_description' => 'Shop the latest smartphones',
                'seo_keywords' => 'smartphones, mobile, phones, devices',
                'commission_rate' => 4.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'parent_id' => 1, // Electronics
                'level' => 1,
                'path' => 'electronics/laptops',
                'name' => 'Laptops',
                'slug' => 'laptops',
                'description' => 'Laptops and portable computers',
                'image' => 'https://via.placeholder.com/300x200/e74c3c/ffffff?text=Laptops',
                'icon' => 'fas fa-laptop',
                'color' => '#e74c3c',
                'sort_order' => 2,
                'is_active' => true,
                'is_featured' => false,
                'status' => true,
                'language' => 'en',
                'seo_title' => 'Laptops - Portable Computers',
                'seo_description' => 'Shop laptops and portable computers',
                'seo_keywords' => 'laptops, computers, portable, notebook',
                'commission_rate' => 3.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'parent_id' => 1, // Electronics
                'level' => 1,
                'path' => 'electronics/tablets',
                'name' => 'Tablets',
                'slug' => 'tablets',
                'description' => 'Tablets and portable devices',
                'image' => 'https://via.placeholder.com/300x200/f39c12/ffffff?text=Tablets',
                'icon' => 'fas fa-tablet-alt',
                'color' => '#f39c12',
                'sort_order' => 3,
                'is_active' => true,
                'is_featured' => false,
                'status' => true,
                'language' => 'en',
                'seo_title' => 'Tablets - Portable Devices',
                'seo_description' => 'Shop tablets and portable devices',
                'seo_keywords' => 'tablets, portable, devices, ipad',
                'commission_rate' => 3.50,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Fashion Categories
            [
                'tenant_id' => 1,
                'parent_id' => null,
                'level' => 0,
                'path' => 'fashion',
                'name' => 'Fashion',
                'slug' => 'fashion',
                'description' => 'Clothing and fashion accessories',
                'image' => 'https://via.placeholder.com/300x200/f39c12/ffffff?text=Fashion',
                'icon' => 'fas fa-tshirt',
                'color' => '#f39c12',
                'sort_order' => 2,
                'is_active' => true,
                'is_featured' => true,
                'status' => true,
                'language' => 'en',
                'seo_title' => 'Fashion - Clothing & Accessories',
                'seo_description' => 'Shop trendy fashion and accessories',
                'seo_keywords' => 'fashion, clothing, accessories, style',
                'commission_rate' => 4.50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'parent_id' => 5, // Fashion
                'level' => 1,
                'path' => 'fashion/womens-clothing',
                'name' => 'Women\'s Clothing',
                'slug' => 'womens-clothing',
                'description' => 'Women\'s apparel and clothing',
                'image' => 'https://via.placeholder.com/300x200/8e44ad/ffffff?text=Womens+Clothing',
                'icon' => 'fas fa-female',
                'color' => '#8e44ad',
                'sort_order' => 1,
                'is_active' => true,
                'is_featured' => true,
                'status' => true,
                'language' => 'en',
                'seo_title' => 'Women\'s Clothing - Fashion Apparel',
                'seo_description' => 'Shop women\'s clothing and fashion',
                'seo_keywords' => 'womens clothing, fashion, apparel, women',
                'commission_rate' => 5.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'parent_id' => 5, // Fashion
                'level' => 1,
                'path' => 'fashion/mens-clothing',
                'name' => 'Men\'s Clothing',
                'slug' => 'mens-clothing',
                'description' => 'Men\'s apparel and clothing',
                'image' => 'https://via.placeholder.com/300x200/34495e/ffffff?text=Mens+Clothing',
                'icon' => 'fas fa-male',
                'color' => '#34495e',
                'sort_order' => 2,
                'is_active' => true,
                'is_featured' => true,
                'status' => true,
                'language' => 'en',
                'seo_title' => 'Men\'s Clothing - Fashion Apparel',
                'seo_description' => 'Shop men\'s clothing and fashion',
                'seo_keywords' => 'mens clothing, fashion, apparel, men',
                'commission_rate' => 5.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Home & Garden Categories
            [
                'tenant_id' => 1,
                'parent_id' => null,
                'level' => 0,
                'path' => 'home-garden',
                'name' => 'Home & Garden',
                'slug' => 'home-garden',
                'description' => 'Home improvement and garden supplies',
                'image' => 'https://via.placeholder.com/300x200/27ae60/ffffff?text=Home+Garden',
                'icon' => 'fas fa-home',
                'color' => '#27ae60',
                'sort_order' => 3,
                'is_active' => true,
                'is_featured' => false,
                'status' => true,
                'language' => 'en',
                'seo_title' => 'Home & Garden - Improvement Supplies',
                'seo_description' => 'Shop home improvement and garden supplies',
                'seo_keywords' => 'home, garden, improvement, supplies',
                'commission_rate' => 4.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'parent_id' => 8, // Home & Garden
                'level' => 1,
                'path' => 'home-garden/furniture',
                'name' => 'Furniture',
                'slug' => 'furniture',
                'description' => 'Home and office furniture',
                'image' => 'https://via.placeholder.com/300x200/16a085/ffffff?text=Furniture',
                'icon' => 'fas fa-couch',
                'color' => '#16a085',
                'sort_order' => 1,
                'is_active' => true,
                'is_featured' => false,
                'status' => true,
                'language' => 'en',
                'seo_title' => 'Furniture - Home & Office',
                'seo_description' => 'Shop home and office furniture',
                'seo_keywords' => 'furniture, home, office, chairs, tables',
                'commission_rate' => 4.50,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Sports & Outdoors Categories
            [
                'tenant_id' => 1,
                'parent_id' => null,
                'level' => 0,
                'path' => 'sports-outdoors',
                'name' => 'Sports & Outdoors',
                'slug' => 'sports-outdoors',
                'description' => 'Sports equipment and outdoor gear',
                'image' => 'https://via.placeholder.com/300x200/27ae60/ffffff?text=Sports',
                'icon' => 'fas fa-running',
                'color' => '#27ae60',
                'sort_order' => 4,
                'is_active' => true,
                'is_featured' => false,
                'status' => true,
                'language' => 'en',
                'seo_title' => 'Sports & Outdoors Equipment',
                'seo_description' => 'Sports equipment and outdoor gear',
                'seo_keywords' => 'sports, outdoors, equipment, gear',
                'commission_rate' => 4.50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'parent_id' => 10, // Sports & Outdoors
                'level' => 1,
                'path' => 'sports-outdoors/fitness',
                'name' => 'Fitness',
                'slug' => 'fitness',
                'description' => 'Fitness equipment and accessories',
                'image' => 'https://via.placeholder.com/300x200/e67e22/ffffff?text=Fitness',
                'icon' => 'fas fa-dumbbell',
                'color' => '#e67e22',
                'sort_order' => 1,
                'is_active' => true,
                'is_featured' => false,
                'status' => true,
                'language' => 'en',
                'seo_title' => 'Fitness Equipment & Accessories',
                'seo_description' => 'Shop fitness equipment and accessories',
                'seo_keywords' => 'fitness, equipment, gym, workout',
                'commission_rate' => 5.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('categories')->insert($categories);
    }
}