<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VendorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $vendors = [
            // Electronics Vendor
            [
                'tenant_id' => 1,
                'user_id' => 2,
                'business_name' => 'TechGear Solutions',
                'business_type' => 'company',
                'business_registration_number' => 'TG-2023-001',
                'tax_id' => 'TAX-TG-001',
                'status' => 'approved',
                'tier' => 'gold',
                'store_name' => 'TechGear Store',
                'store_slug' => 'techgear-store',
                'store_description' => 'Premium electronics and gadgets for tech enthusiasts.',
                'store_logo' => 'https://via.placeholder.com/200/3498db/ffffff?text=TG',
                'store_banner' => 'https://via.placeholder.com/1200x300/3498db/ffffff?text=TechGear',
                'store_theme' => json_encode(['primary_color' => '#3498db', 'secondary_color' => '#2c3e50']),
                'store_policies' => json_encode(['shipping' => 'Free shipping over $50', 'returns' => '30-day policy']),
                'seo_settings' => json_encode(['meta_title' => 'TechGear Store', 'meta_description' => 'Premium electronics']),
                'social_media' => json_encode(['facebook' => 'https://facebook.com/techgear']),
                'contact_email' => 'contact@techgear.com',
                'contact_phone' => '+1-555-1001',
                'address' => '123 Tech Street',
                'city' => 'San Francisco',
                'state' => 'CA',
                'country' => 'USA',
                'postal_code' => '94105',
                'commission_rate' => 3.50,
                'subscription_fee' => 99.99,
                'subscription_plan' => 'premium',
                'verified' => true,
                'verification_documents' => json_encode(['business_license' => 'verified']),
                'verified_at' => now()->subDays(30),
                'approved_at' => now()->subDays(30),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Fashion Vendor
            [
                'tenant_id' => 1,
                'user_id' => 3,
                'business_name' => 'Fashion Forward',
                'business_type' => 'individual',
                'business_registration_number' => null,
                'tax_id' => 'TAX-FF-002',
                'status' => 'approved',
                'tier' => 'silver',
                'store_name' => 'Fashion Forward Boutique',
                'store_slug' => 'fashion-forward-boutique',
                'store_description' => 'Trendy fashion and accessories for the modern woman.',
                'store_logo' => 'https://via.placeholder.com/200/e74c3c/ffffff?text=FF',
                'store_banner' => 'https://via.placeholder.com/1200x300/e74c3c/ffffff?text=Fashion',
                'store_theme' => json_encode(['primary_color' => '#e74c3c', 'secondary_color' => '#f39c12']),
                'store_policies' => json_encode(['shipping' => 'Free shipping over $75', 'returns' => '14-day policy']),
                'seo_settings' => json_encode(['meta_title' => 'Fashion Forward', 'meta_description' => 'Trendy fashion']),
                'social_media' => json_encode(['instagram' => 'https://instagram.com/fashionforward']),
                'contact_email' => 'hello@fashionforward.com',
                'contact_phone' => '+1-555-1002',
                'address' => '456 Fashion Ave',
                'city' => 'New York',
                'state' => 'NY',
                'country' => 'USA',
                'postal_code' => '10001',
                'commission_rate' => 4.00,
                'subscription_fee' => 49.99,
                'subscription_plan' => 'basic',
                'verified' => true,
                'verification_documents' => json_encode(['identity_verification' => 'verified']),
                'verified_at' => now()->subDays(15),
                'approved_at' => now()->subDays(15),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Real Estate Vendor
            [
                'tenant_id' => 3,
                'user_id' => 6,
                'business_name' => 'Martinez Real Estate Group',
                'business_type' => 'company',
                'business_registration_number' => 'MRE-2023-001',
                'tax_id' => 'TAX-MRE-001',
                'status' => 'approved',
                'tier' => 'platinum',
                'store_name' => 'Martinez Properties',
                'store_slug' => 'martinez-properties',
                'store_description' => 'Premier real estate services specializing in luxury properties.',
                'store_logo' => 'https://via.placeholder.com/200/27ae60/ffffff?text=MR',
                'store_banner' => 'https://via.placeholder.com/1200x300/27ae60/ffffff?text=Martinez',
                'store_theme' => json_encode(['primary_color' => '#27ae60', 'secondary_color' => '#2ecc71']),
                'store_policies' => json_encode(['commission' => '3% commission', 'consultation' => 'Free consultation']),
                'seo_settings' => json_encode(['meta_title' => 'Martinez Properties', 'meta_description' => 'Luxury real estate']),
                'social_media' => json_encode(['facebook' => 'https://facebook.com/martinezproperties']),
                'contact_email' => 'info@martinezproperties.com',
                'contact_phone' => '+1-555-2001',
                'address' => '789 Real Estate Blvd',
                'city' => 'Los Angeles',
                'state' => 'CA',
                'country' => 'USA',
                'postal_code' => '90210',
                'commission_rate' => 3.00,
                'subscription_fee' => 199.99,
                'subscription_plan' => 'premium',
                'verified' => true,
                'verification_documents' => json_encode(['real_estate_license' => 'verified']),
                'verified_at' => now()->subDays(45),
                'approved_at' => now()->subDays(45),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Auto Trade Vendor
            [
                'tenant_id' => 4,
                'user_id' => 8,
                'business_name' => 'Brown\'s Auto Sales',
                'business_type' => 'company',
                'business_registration_number' => 'BAS-2023-001',
                'tax_id' => 'TAX-BAS-001',
                'status' => 'approved',
                'tier' => 'gold',
                'store_name' => 'Brown\'s Auto Hub',
                'store_slug' => 'browns-auto-hub',
                'store_description' => 'Quality pre-owned vehicles with comprehensive warranties.',
                'store_logo' => 'https://via.placeholder.com/200/8e44ad/ffffff?text=BA',
                'store_banner' => 'https://via.placeholder.com/1200x300/8e44ad/ffffff?text=Browns+Auto',
                'store_theme' => json_encode(['primary_color' => '#8e44ad', 'secondary_color' => '#9b59b6']),
                'store_policies' => json_encode(['warranty' => '6-month warranty', 'financing' => 'Flexible financing']),
                'seo_settings' => json_encode(['meta_title' => 'Brown\'s Auto Hub', 'meta_description' => 'Quality pre-owned vehicles']),
                'social_media' => json_encode(['facebook' => 'https://facebook.com/brownsauto']),
                'contact_email' => 'sales@brownsauto.com',
                'contact_phone' => '+1-555-3001',
                'address' => '321 Auto Row',
                'city' => 'Chicago',
                'state' => 'IL',
                'country' => 'USA',
                'postal_code' => '60601',
                'commission_rate' => 2.50,
                'subscription_fee' => 149.99,
                'subscription_plan' => 'premium',
                'verified' => true,
                'verification_documents' => json_encode(['dealer_license' => 'verified']),
                'verified_at' => now()->subDays(20),
                'approved_at' => now()->subDays(20),
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        DB::table('vendors')->insert($vendors);
    }
}